import json
import os
from app.schemas import AppPlan, EntitySchema
from app.services.sql_generator import generate_sql

GENERATED_ROOT = os.path.join(os.getcwd(), "generated-apps")


def _input_for_field(f) -> str:
    if f.type == "boolean":
        return f'<input type="checkbox" name="{f.name}" />'
    if f.type == "textarea":
        return f'<textarea name="{f.name}" className="border rounded p-2 w-full" />'
    if f.type == "select":
        opts = "".join(f'<option value="{o}">{o}</option>' for o in (f.options or []))
        return f'<select name="{f.name}" className="border rounded p-2 w-full">{opts}</select>'
    html_type = "number" if f.type == "number" else "date" if f.type == "date" else "text"
    required = "required" if f.required else ""
    return f'<input type="{html_type}" name="{f.name}" className="border rounded p-2 w-full" {required} />'


def _generate_entity_page(entity: EntitySchema) -> str:
    table = entity.plural.lower()
    form_fields = "\n".join(
        f"        <label>{f.name}</label>\n        {_input_for_field(f)}" for f in entity.fields
    )
    table_headers = "".join(f"<th>{f.name}</th>" for f in entity.fields)
    table_cells = "".join(f"<td>{{item.{f.name}}}</td>" for f in entity.fields)

    return f"""// Auto-generated by NovaBuild — entity: {entity.name}
"use client";
import {{ useEffect, useState }} from "react";
import {{ supabase }} from "@/lib/supabase";

export default function {entity.name}Page() {{
  const [items, setItems] = useState<any[]>([]);

  async function load() {{
    const {{ data }} = await supabase.from("{table}").select("*").order("created_at", {{ ascending: false }});
    setItems(data ?? []);
  }}

  useEffect(() => {{ load(); }}, []);

  async function handleSubmit(e: React.FormEvent<HTMLFormElement>) {{
    e.preventDefault();
    const formData = new FormData(e.currentTarget);
    const payload = Object.fromEntries(formData.entries());
    const {{ data: {{ user }} }} = await supabase.auth.getUser();
    await supabase.from("{table}").insert({{ ...payload, user_id: user?.id }});
    e.currentTarget.reset();
    load();
  }}

  async function handleDelete(id: string) {{
    await supabase.from("{table}").delete().eq("id", id);
    load();
  }}

  return (
    <div>
      <h1>{entity.plural}</h1>
      <form onSubmit={{handleSubmit}}>
{form_fields}
        <button type="submit">Add {entity.name}</button>
      </form>
      <table>
        <thead><tr>{table_headers}<th></th></tr></thead>
        <tbody>
          {{items.map((item) => (
            <tr key={{item.id}}>
              {table_cells}
              <td><button onClick={{() => handleDelete(item.id)}}>Delete</button></td>
            </tr>
          ))}}
        </tbody>
      </table>
    </div>
  );
}}
"""

def _entity_filename(entity: EntitySchema) -> str:
    return f"pages/{entity.plural.lower()}.tsx"


def write_entity_page(base_dir: str, entity: EntitySchema) -> str:
    filename = _entity_filename(entity)
    path = os.path.join(base_dir, filename)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        f.write(_generate_entity_page(entity))
    return filename


def remove_entity_page(base_dir: str, entity_plural: str) -> str:
    filename = f"pages/{entity_plural.lower()}.tsx"
    path = os.path.join(base_dir, filename)
    if os.path.isfile(path):
        os.remove(path)
    return filename


def write_plan_json(base_dir: str, plan: AppPlan):
    with open(os.path.join(base_dir, "plan.json"), "w") as f:
        f.write(plan.model_dump_json(indent=2))


def write_schema_sql(base_dir: str, plan: AppPlan) -> str:
    sql = generate_sql(plan)
    with open(os.path.join(base_dir, "schema.sql"), "w") as f:
        f.write(sql)
    return sql


def generate_project_files(plan: AppPlan, project_id: str) -> dict:
    base_dir = os.path.join(GENERATED_ROOT, project_id)
    os.makedirs(os.path.join(base_dir, "pages"), exist_ok=True)

    write_plan_json(base_dir, plan)
    write_schema_sql(base_dir, plan)

    files = ["plan.json", "schema.sql"]
    for entity in plan.entities:
        files.append(write_entity_page(base_dir, entity))

    return {"project_id": project_id, "dir": base_dir, "files": files}